version: "3"
services:
  client:
    build: .
    # ports: # remove the ports so the swag container can use them
    # - 0.0.0.0:3011:80

  swag:
    image: lscr.io/linuxserver/swag
    container_name: joshswag
    cap_add:
      - NET_ADMIN
    env_file:
    - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=stormgateisawesome.duckdns.org
      - VALIDATION=duckdns
      - STAGING=false
    volumes:
      - /home/josh/data/swag:/config
    ports:
    - 0.0.0.0:3141:443
    restart: unless-stopped